language: node_js
node_js:
  - 13.14.0

services:
  - docker

before_script: sudo apt-get install docker-compose

script:
  - docker-compose -f ./docker-compose.test.yaml up --abort-on-container-exit --exit-code-from pecunia-web-server