version: "3.8"

services:
  pecunia-web-server:
    build:
      context: ./
    container_name: pecunia-web-server
    restart: "no"
    environment: 
      DB_TIMEOUT: 60
      NODE_ENV: test
      CI: "true"
      Server__Port: 3005
      Database__Host: "pecunia-db"
      Database__Port: 3306
      Database__User: "user"
      Database__Password: "password"
      Database__Database: "pecunia_db"
      Logger__Level: "error"
      Logger__Stream: "bunyan-debug-stream"
      Logger__ShowHeaders: "true"
      Admin__Email: "admin@email.com"
      Admin__Password: "j,?brk-:b;ckP2{Hn@zSq!8h])JP2?"
      JWT_SECRET_KEY: "QGnDv@MaEh@Cza7bNEUZ)ZihBbW:Fi?RFm&Aw@fByr%GSS///.r*2H,@=akfiiZuN+!;nr!!r5KDgh3UVVfrjb?Szxx[NNLW9VgHXwq-:-(p%dzW-rxxqYp)Umgex5vDL);deZ_aQchTjVUYvF],b_GpUXa!Q!z=[wd7SPbhVzDq-=iZMW/L]NiK(:;#WZqR]&*qLY;a4:gCMAUN-5?&FX3W7g%f?H{f=QecYU4,uphNB5q+Ex]bdd(%HPz__2Z("
      coverage: "true"
    ports:
      - "3005:3005"
    volumes:
      - "./:/home/node/app"
      - /home/node/app/node_modules/

  pecunia-db:
    image: mysql:5.7.31
    container_name: pecunia-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pecunia_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      # - ./database/data:/var/lib/mysql