version: "3.8"

services:
  pecunia-web-server:
    build:
      context: ./
    container_name: pecunia-web-server
    restart: always
    environment: 
      DB_TIMEOUT: 60
      NODE_ENV: development
      Server__Port: 3005
      Database__Host: "pecunia-db"
      Database__Port: 3306
      Database__User: "user"
      Database__Password: "password"
      Database__Database: "pecunia_db"
      Logger__Level: "debug"
      Logger__Stream: "bunyan-debug-stream"
      Logger__ShowHeaders: "true"
    ports:
      - "3005:3005"
    volumes:
      - "./:/home/node/app"

  pecunia-db:
    image: mysql:5.7.31
    container_name: pecunia-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pecunia_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d