version: "3.8"

services:
  pecunia-web-server:
    build:
      context: ./
    container_name: pecunia-web-server
    restart: always
    environment: 
      DB_TIMEOUT: 60
      NODE_ENV: development
      Server__Port: 3005
      Database__Host: "pecunia-db"
      Database__Port: 3306
      Database__User: "user"
      Database__Password: "password"
      Database__Database: "pecunia_db"
      Logger__Level: "debug"
      Logger__Stream: "bunyan-debug-stream"
      Logger__ShowHeaders: "true"
      Admin__Email: "admin@email.com"
      Admin__Password: "gi:NyUkP.5_5S3VW%AWeZJD_7q&3qt"
      JWT_SECRET_KEY: "v[tn;A_S6NrUb=fHX%yu*3[HUkkn+8McYJLC*5RVTi4jY)P8fqt7xcr+{_5hXU]rffiDuL6T;bq38kF%f-}bE{dMd6VZ&QrgLhuGSP#HWxmP4F2Cc&.Rn2Fdv4U@=ue2mTY.UW2KP.z]U*}5w*,yQMfQ*-C5=-9[LCa9@*Z5cWA}UK(yUWxD=x}]j;;AG)(B=&kYq[-D(H_WCU)v&GrrL-?E_+7zkNYjVh#v-!@J+ke7NPC&v@CS?bAu*z#!QQ.]"
    ports:
      - "3005:3005"
    volumes:
      - "./:/home/node/app"
      - /home/node/app/node_modules/

  pecunia-db:
    image: mysql:5.7.31
    container_name: pecunia-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pecunia_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d

  pecunia-adminer:
    container_name: pecunia-adminer
    image: adminer:4.7.7
    restart: always
    logging:
      driver: none
    environment:
      ADMINER_DEFAULT_SERVER: pecunia-db
    ports:
      - 8080:8080